# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[(b'B', b'blog'), (b'T', b'tech')], default=b'B', max_length=1),
        ),
    ]
