# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-02-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
